#define WIDTH 1
#define MAX_LEVEL 100
#define WIN_WIDTH 1200
#define WIN_HEIGHT 800

#define FONT_S GLUT_BITMAP_HELVETICA_10
#define FONT_M GLUT_BITMAP_HELVETICA_12
#define FONT_B GLUT_BITMAP_HELVETICA_18
